<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>svg_Password_lucide lucide-eye h-4 w-4</name>
   <tag></tag>
   <elementGuidId>ca5f9b90-0881-4acb-bfd2-d967729a80cf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>svg.lucide.lucide-eye.h-4.w-4</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Password*'])[1]/following::*[name()='svg'][1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>div >> internal:has-text=/^Password\*$/ >> internal:role=button</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>5ce1bd51-457c-4708-9d8d-63caccf265ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/2000/svg</value>
      <webElementGuid>c3772459-fc31-49bc-b27b-07a8fd32403b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>24</value>
      <webElementGuid>8987976e-ca91-4784-87df-cd09a9f9407c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>24</value>
      <webElementGuid>b6f4b96f-75df-47a5-846d-d9ad27a9c5aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 24 24</value>
      <webElementGuid>288343de-3cb6-4bb6-86d5-a7325ddbab37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>02690625-bd4e-4f3b-ba9e-d079c118b191</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke</name>
      <type>Main</type>
      <value>currentColor</value>
      <webElementGuid>3bd2815c-68c4-4e58-b5e9-7c4ce4efea3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-width</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>1771e747-bb03-4ba7-ad68-f9dd66028c28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-linecap</name>
      <type>Main</type>
      <value>round</value>
      <webElementGuid>af4d19a5-f0bb-4af6-9080-6f9b3a3b7fbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-linejoin</name>
      <type>Main</type>
      <value>round</value>
      <webElementGuid>e62b1905-9a16-4bfa-9d4b-d1253b27c450</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lucide lucide-eye h-4 w-4</value>
      <webElementGuid>16fb8992-2e25-454f-b813-fd5b3b8dba7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;__variable_518cef __variable_e8ce0c light&quot;]/body[@class=&quot;font-roboto&quot;]/div[@class=&quot;flex min-h-screen flex-col&quot;]/div[@class=&quot;grid flex-grow grid-cols-1 md:grid-cols-2 relative&quot;]/div[@class=&quot;flex flex-col items-center justify-center p-8&quot;]/div[@class=&quot;w-full max-w-[500px] space-y-6&quot;]/form[@class=&quot;space-y-4&quot;]/div[@class=&quot;space-y-2&quot;]/div[@class=&quot;relative&quot;]/button[@class=&quot;absolute right-3 top-1/2 -translate-y-1/2 text-gray-500&quot;]/svg[@class=&quot;lucide lucide-eye h-4 w-4&quot;]</value>
      <webElementGuid>67b20427-fa10-437d-8229-bcf2dcb8e686</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password*'])[1]/following::*[name()='svg'][1]</value>
      <webElementGuid>0eb51580-9584-4ef4-972a-826d7ed5376b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email ID*'])[1]/following::*[name()='svg'][1]</value>
      <webElementGuid>4ca7c9c1-11ad-46c1-89e1-48548b727b19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Forgot Password?'])[1]/preceding::*[name()='svg'][1]</value>
      <webElementGuid>a33e5651-64ff-4631-b3b6-6b832af07f14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Continue'])[1]/preceding::*[name()='svg'][1]</value>
      <webElementGuid>70c4a47a-15a7-4dec-b844-21649d7f6153</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
